apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: alexanderkarpovich/platformservice:latest
        env:
        - name: platformsdbPassword
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
---
# Cluster IP service
apiVersion: v1
kind: Service
metadata:
  name: platformservice-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: platformgrpc
    protocol: TCP
    port: 500
    targetPort: 500
